[project]
name = "xox"
version = "0.1.0"
description = "Tic Tac Toe Game."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "maturin>=1.8.6",
    "pydantic>=2.11.4",
    "pyfiglet>=1.0.2",
    "rich>=14.0.0",
    "ruff>=0.11.10",
]
